---
title: "Untitled"
author: "Marco Garofalo"
date: "1/26/2021"
output: html_document
runtime: shiny
resource_files:
- data/G2t_T24_L10_msq0-4.900000_msq1-4.900000_l02.500000_l12.500000_mu5.000000_g0.000000_rep0_output
- data/G2t_T24_L10_msq0-4.950000_msq1-4.900000_l02.500000_l12.500000_mu5.000000_g0.000000_rep0_output
- data/G2t_T24_L10_msq0-4.950000_msq1-4.900000_l02.500000_l12.500000_mu5.000000_g0.000000_rep1_output
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(plotly)
library(tidyverse)
library(htmlwidgets)
library(pander)
library(latex2exp)
library(knitr)
library(dplyr) #data frame manipulation
require(scales) # to access break formatting functions
library(shiny)
library(shinyWidgets)
library(ggrepel)
panderOptions('knitr.auto.asis', FALSE)
```

```{r , echo=FALSE}
if(!exists("Rread_block.R", mode="function")) source("Rread_block.R")
if(!exists("print_error.R", mode="function")) source("print_error.R")
if(!exists("print_error.R", mode="function")) source("plot_routines.R")
```

```{r , echo=FALSE, results="asis"}
inputPanel(
  selectInput("L", label = "L",
              choices =as.integer( c(10, 20,40)), selected = 20),
  selectInput("T", label = "T",
              choices =as.integer( c(24, 48,96)), selected = 48),
  selectInput("msq0", label = "msq0",
              choices = c(-4.9,-4.95,-4.925,-4.98,-4.99,-5.0), selected = -4.925),
  selectInput("msq1", label = "msq1",
              choices =c(-4.9,-4.89,-4.85), selected = -4.85),
  selectInput("l0", label = "$\\lambda_0$",
              choices =c(2.5), selected = 2.5),
  selectInput("l1", label = "lambda_1",
              choices =c(2.5), selected = 2.5),
  selectInput("mu", label = "mu",
              choices =c(5), selected = 5),
  selectInput("g", label = "g",
              choices =c(0.0), selected = 0),
  selectInput("rep", label = "rep",
              choices =c(0,1,2), selected = 1),
  selectInput("Obs", label = "Obs",
              choices =c("meff0","meff1","E2_0","E2_1","E2","E3_0","E3_1","E3",
                         "C4_BH","E2_01", "meff(E2_01)"),
              selected = "C4_BH"),
  selectInput("logscale", label = "logscale",
              choices =c("no","yes"), selected = "no")
  
#   pickerInput(
#   inputId = "manyObs",
#   label = "Obs",
#   choices =c("meff0","meff1","E2_0","E2_1","E2","E3_0","E3_1","E3",
#                          "C4_BH","E2_01", "meff(E2_01)"),
#   options = list(
#     `actions-box` = TRUE,
#     size = 10,
#     `selected-text-format` = "count > 3"
#     
#   ),
#   multiple = TRUE,
#   selected = "C4_BH"
# )
)

```

```{r eval=FALSE, include=FALSE}
tmp<-reactive({
  
  return(input$manyObs)
})

tmp1<-reactive({
  l<-list()
  for (f in input$manyObs){
    l<-append(l,f)
  }
  return(l)
})
renderPrint(input$manyObs)
renderPrint(tmp1())
```

```{r, echo=FALSE}
file<-reactive({
  T<-as.integer(input$T)
  L<-as.integer(input$L)
  msq0<-as.double(input$msq0)
  msq1<-as.double(input$msq1)
  l0<-as.double(input$l0)
  l1<-as.double(input$l1)
  mu<-as.double(input$mu)
  g <- as.double(input$g)
  rep<-as.integer(input$rep)
  dir <- "/home/marco/analysis/phi4/tuning_masses/out" 
  #dir <- "Data" 
  
  file=sprintf("%s/G2t_T%d_L%d_msq0%.6f_msq1%.6f_l0%.6f_l1%.6f_mu%.6f_g%.6f_rep%d_output",                         dir, T, L,  msq0,  msq1,  l0,  l1,  mu,  g,  rep)
  return(file)
})
file_meff<-reactive({
  T<-as.integer(input$T)
  L<-as.integer(input$L)
  msq0<-as.double(input$msq0)
  msq1<-as.double(input$msq1)
  l0<-as.double(input$l0)
  l1<-as.double(input$l1)
  mu<-as.double(input$mu)
  g <- as.double(input$g)
  rep<-as.integer(input$rep)
  dir <- "/home/marco/analysis/phi4/tuning_masses/out" 
  #dir <- "Data" 
  
  file=sprintf("%s/G2t_T%d_L%d_msq0%.6f_msq1%.6f_l0%.6f_l1%.6f_mu%.6f_g%.6f_rep%d_meff_correlators",                         dir, T, L,  msq0,  msq1,  l0,  l1,  mu,  g,  rep)
  return(file)
})


n_and_plot<-reactive({
  if (input$Obs=="meff0")   { n<- 2 ;fun<-  myggplot    ; nmeff<-1         }
  if (input$Obs=="meff1")    {n<- 3 ;fun<-  myggplot  ; nmeff<-2   }
  if (input$Obs=="E2_0")  {  n<- 5;fun<-  myggplot    ; nmeff<-3 }
  if (input$Obs=="E2_1")  {  n<- 6; fun<-  myggplot   ; nmeff<-4  }
  if (input$Obs=="E2")    {  n<- 7; fun<-  myggplot   ; nmeff<-5  }
  if (input$Obs=="E3_0")  {  n<- 8; fun<-  my_fit_ggplot  ; nmeff<-6   }
  if (input$Obs=="E3_1")   { n<- 9; fun<-  my_fit_ggplot  ; nmeff<-7   }
  if (input$Obs=="E3")    {n<- 10 ; fun<-  my_fit_ggplot  ; nmeff<-8   }
  if (input$Obs=="C4_BH")    {n<- 13; fun<-  my_fit_ggplot  ; nmeff<-11     }
  if (input$Obs=="E2_01")    {n<- 20; fun<-  my_fit_ggplot    ; nmeff<-12   }
  if (input$Obs=="meff(E2_01)")    {n<- 21; fun<-  my_fit_ggplot  ; nmeff<-12     }

  return (c(n,fun, nmeff))
})

```

```{r, echo=FALSE}
gg_new<-reactive({  
  file<-file()
  n1<-n_and_plot()
  n<-n1[[1]]
  T<-as.integer(input$T)
  mt<-read_df(file)
  
  d<- get_block_n(mt,n)
  fit<- get_fit_n(mt,n)
  fit_range<- get_plateaux_range(mt,n)
      
  #plot data
  tmp<-n_and_plot()[[2]]
  gg<-tmp(d,fit,fit_range,T/2,input$logscale)
  

  #plot(gg)
  return(gg)
})
gg_residual<-reactive({  
  file<-file_meff()
  n1<-n_and_plot()
  n<-n1[[3]]
  T<-as.integer(input$T)
  mt<-read_df(file)
  
  d<- get_block_n(mt,n)
  fit<- get_fit_n(mt,n)
  fit_range<- get_plateaux_range(mt,n)
  
  #plot data
  tmp<-n_and_plot()[[2]]
  gg<-tmp(d,fit,fit_range,T/2, input$logscale)

  return(gg)
})



mass_tables_01<-reactive({  

    df<- data.frame(  "meff0"=c(0),  "meff1"=c(0) ,      "E2_01"=c(0),    
    "DE2_01"=c(0)   , "a_Luscher"=c(0)  , "a_BH_01"=c(0)    )
   
    file<-file()
    T<-as.integer(input$T)

    mt<-read_df(file)
    fit<- get_fit_n(mt,2)
    fit1<- get_fit_n(mt,3)
    fit01<- get_fit_n(mt,20)
    fitBH<- get_fit_n(mt,13)
    df[ 1,]<- list( mean_print(fit[1,1], fit[1,2]), 
                    mean_print(fit1[1,1], fit1[1,2]),
                    mean_print(fit01[1,1], fit01[1,2]),
                    mean_print(fit01[2,3], fit01[2,4]) ,
                    mean_print(fit01[2,1], fit01[2,2]),
                    mean_print(fitBH[1,1], fitBH[1,2])        )
    return(df)
    
})

mass_tables_0<-reactive({  

    df<- data.frame(  "meff0"=c(0),  "meff1"=c(0) ,      "E2_0"=c(0),    
    "DE2_0"=c(0)   , "a_Luscher"=c(0)  , "a_BH_0"=c(0)    )
   
    file<-file()
    T<-as.integer(input$T)

    mt<-read_df(file)
    fit<- get_fit_n(mt,2)
    fit1<- get_fit_n(mt,3)
    fit01<- get_fit_n(mt,5)
    fitBH<- get_fit_n(mt,11)
    df[ 1,]<- list( mean_print(fit[1,1], fit[1,2]), 
                    mean_print(fit1[1,1], fit1[1,2]),
                    mean_print(fit01[1,1], fit01[1,2]),
                    mean_print(fit01[2,3], fit01[2,4]) ,
                    mean_print(fit01[2,1], fit01[2,2]),
                    mean_print(fitBH[1,1], fitBH[1,2])        )
    return(df)
    
})

mass_tables_1<-reactive({  

    df<- data.frame(  "meff0"=c(0),  "meff1"=c(0) ,      "E2_1"=c(0),    
    "DE2_0"=c(0)   , "a_Luscher"=c(0)  , "a_BH_1"=c(0)    )
   
    file<-file()
    T<-as.integer(input$T)

    mt<-read_df(file)
    fit<- get_fit_n(mt,2)
    fit1<- get_fit_n(mt,3)
    fit01<- get_fit_n(mt,6)
    fitBH<- get_fit_n(mt,12)
    df[ 1,]<- list( mean_print(fit[1,1], fit[1,2]), 
                    mean_print(fit1[1,1], fit1[1,2]),
                    mean_print(fit01[1,1], fit01[1,2]),
                    mean_print(fit01[2,3], fit01[2,4]) ,
                    mean_print(fit01[2,1], fit01[2,2]),
                    mean_print(fitBH[1,1], fitBH[1,2])        )
    return(df)
    
})
```

```{r, echo=FALSE}

renderTable( mass_tables_01())
renderTable( mass_tables_0())
renderTable( mass_tables_1())
```

```{r , echo=FALSE, results="asis", include=FALSE}
ggly<-reactive({
  ggly<-ggplotly(gg_new())
  return(ggly)
})
  
  renderPrint({file()})
  #renderPlot(gg())
  renderPlotly(ggly())
  

```



```{r , echo=FALSE, results="asis", include=FALSE}
renderText({"correlator:"})

renderText(input$Obs)


gg2ly<-reactive({
  ggly<-ggplotly(gg_residual()) 
  return(ggly)
})
  
 renderPlotly(gg2ly())

  
  mypl<-renderText({"$m_0^2=$"})
  mypl()

```

```{r, echo=FALSE}
inputPanel(
  
  #checkboxGroupInput("manyObs", label = "Obs",
  #            choices =c("meff0","meff1","E2_0","E2_1","E2","E3_0","E3_1","E3",
  #                       "C4_BH","E2_01", "meff(E2_01)"),
  #            selected = "C4_BH"),
  pickerInput(
  inputId = "manyObs",
  label = "Obs",
  choices =c("meff0","meff1","E2_0","E2_1","E2","E3_0","E3_1","E3",
                         "C4_BH","E2_01"),
  options = list(
    `actions-box` = TRUE,
    size = 10
   ,`selected-text-format` = "count > 3"
    
  ),
  multiple = TRUE,
  selected = "C4_BH"
)
)
```

```{r, echo=FALSE}
n_and_plot_many<-function(input)({
  if (input=="meff0")   { n<- 2 ;fun<-  myggplot    ; nmeff<-1         }
  if (input=="meff1")    {n<- 3 ;fun<-  myggplot  ; nmeff<-2   }
  if (input=="E2_0")  {  n<- 5;fun<-  myggplot    ; nmeff<-3 }
  if (input=="E2_1")  {  n<- 6; fun<-  myggplot   ; nmeff<-4  }
  if (input=="E2")    {  n<- 7; fun<-  myggplot   ; nmeff<-5  }
  if (input=="E3_0")  {  n<- 8; fun<-  my_fit_ggplot  ; nmeff<-6   }
  if (input=="E3_1")   { n<- 9; fun<-  my_fit_ggplot  ; nmeff<-7   }
  if (input=="E3")    {n<- 10 ; fun<-  my_fit_ggplot  ; nmeff<-8   }
  if (input=="C4_BH")    {n<- 13; fun<-  my_fit_ggplot  ; nmeff<-11     }
  if (input=="E2_01")    {n<- 20; fun<-  my_fit_ggplot    ; nmeff<-12   }

  return (c(n,fun, nmeff))
})



gg_many<-reactive({  
  gg<- ggplot()
  for (myobs in input$manyObs){
  file<-file()
  n1<-n_and_plot_many(myobs)
  n<-n1[[1]]
  T<-as.integer(input$T)
  mt<-read_df(file)
  
  d<- get_block_n(mt,n)
  fit<- get_fit_n(mt,n)
  fit_range<- get_plateaux_range(mt,n)
      
  #plot data
  #gg<-  many_fit_ggplot(d,fit,fit_range,T/2,input$logscale,gg,  myobs  )
  
  if(myobs=="meff0")
  gg<-  many_fit_ggplot(d,fit,fit_range,T/2,input$logscale,gg,"meff0")
  if(myobs=="meff1")
  gg<-  many_fit_ggplot(d,fit,fit_range,T/2,input$logscale,gg,"meff1")
  if(myobs=="E2_0")
  gg<-  many_fit_ggplot(d,fit,fit_range,T/2,input$logscale,gg,"E2_0")
  if(myobs=="E2_1")
  gg<-  many_fit_ggplot(d,fit,fit_range,T/2,input$logscale,gg,"E2_1")
  if(myobs=="E2")
  gg<-  many_fit_ggplot(d,fit,fit_range,T/2,input$logscale,gg,"E2")
  if(myobs=="E3_0")
  gg<-  many_fit_ggplot(d,fit,fit_range,T/2,input$logscale,gg,"E3_0")
  if(myobs=="E3_1")
  gg<-  many_fit_ggplot(d,fit,fit_range,T/2,input$logscale,gg,"E3_1")
  if(myobs=="E3")
  gg<-  many_fit_ggplot(d,fit,fit_range,T/2,input$logscale,gg,"E3")
  if(myobs=="C4_BH")
  gg<-  many_fit_ggplot(d,fit,fit_range,T/2,input$logscale,gg,"C4_BH")
  if(myobs=="E2_01")
  gg<-  many_fit_ggplot(d,fit,fit_range,T/2,input$logscale,gg,"E2_01")
  
}
  
  return(gg)
})
gg_many_meff<-reactive({  
 gg<- ggplot()
  for (myobs in input$manyObs){
  file<-file_meff()
  n1<-n_and_plot_many(myobs)
  n<-n1[[3]]
  T<-as.integer(input$T)
  mt<-read_df(file)
  
  d<- get_block_n(mt,n)
  fit<- get_fit_n(mt,n)
  fit_range<- get_plateaux_range(mt,n)
      
  #plot data
  #tmp<-tostring(myobs)

  #gg<-  many_fit_ggplot(d,fit,fit_range,T/2,input$logscale,gg,  myobs  )
  
  if(myobs=="meff0")
  gg<-  many_fit_ggplot(d,fit,fit_range,T/2,input$logscale,gg,"meff0")
  if(myobs=="meff1")
  gg<-  many_fit_ggplot(d,fit,fit_range,T/2,input$logscale,gg,"meff1")
  if(myobs=="E2_0")
  gg<-  many_fit_ggplot(d,fit,fit_range,T/2,input$logscale,gg,"E2_0")
  if(myobs=="E2_1")
  gg<-  many_fit_ggplot(d,fit,fit_range,T/2,input$logscale,gg,"E2_1")
  if(myobs=="E2")
  gg<-  many_fit_ggplot(d,fit,fit_range,T/2,input$logscale,gg,"E2")
  if(myobs=="E3_0")
  gg<-  many_fit_ggplot(d,fit,fit_range,T/2,input$logscale,gg,"E3_0")
  if(myobs=="E3_1")
  gg<-  many_fit_ggplot(d,fit,fit_range,T/2,input$logscale,gg,"E3_1")
  if(myobs=="E3")
  gg<-  many_fit_ggplot(d,fit,fit_range,T/2,input$logscale,gg,"E3")
  if(myobs=="C4_BH")
  gg<-  many_fit_ggplot(d,fit,fit_range,T/2,input$logscale,gg,"C4_BH")
  if(myobs=="E2_01")
  gg<-  many_fit_ggplot(d,fit,fit_range,T/2,input$logscale,gg,"E2_01")
  
}
  
  return(gg)
})
```


```{r echo=FALSE, warning=FALSE}
renderPlotly(ggplotly(gg_many()  )  )

```

## Effective Mass correlator $\log \frac{c(t)}{c(t+1)}$

```{r echo=FALSE, warning=FALSE}
renderPlotly(ggplotly(gg_many_meff()  )  )

```

# Summary Table

```{r echo=FALSE, warning=FALSE}

df_tot_compact<- data.frame(  "L"=c(0),"T"=c(0),
                      "msq0"=c(0), "msq1"=c(0),
                    "meff0"=c(0),  "meff1"=c(0) , 
               #   "E2_0"=c(0),  "E2_1"=c(0),
               #   "E3_0"=c(0),  "E3_1"=c(0),
                  "a_BH"=c(0),
                  "a_luscher"=c(0) ,"E2"=c(0) ,"DeltaE2"=c(0) ,
                  "lambda0"=c(0) , "lambda1"=c(0),
                  "mu"=c(0), "g"=c(0), "rep"=c(0)  )
count<-1
for (dir in c( "/home/marco/analysis/phi4/tuning_masses/out" )){
#for (dir in c( "Data" )){  
  for (msq1 in c(-4.9,-4.89,-4.85)){
    for (msq0 in c(-4.9,-4.95,-4.925,-4.98,-4.99,-5.0)){
      for (l0 in c(2.5)){  
        for (l1 in c(2.5)){    
          for (mu in c(5.0)){    
            for (g in c(0)){
              for (L in c(10,20,40)){
                for (T in c(24,48)){
                  for (rep in c(0,1,2)){
                    file1=sprintf("%s/G2t_T%d_L%d_msq0%.6f_msq1%.6f_l0%.6f_l1%.6f_mu%.6f_g%.6f_rep%d_output",
                                 dir,T,L,msq0,msq1,l0,l1,mu,g,rep)
                    if (file.exists(file1)){
                      
   
    
    columns_file<-c(1:20)  
    mylist<- list(  L,T)
    mylist  <-append(mylist, list(msq0, msq1 ))
    
    
    mt<-read_df(file1)
    
    fit<- get_fit_n(mt,2)
    mylist  <- append(mylist, mean_print(fit[1,1], fit[1,2])) 
    fit<- get_fit_n(mt,3)
    mylist  <- append(mylist, mean_print(fit[1,1], fit[1,2]))
    #E2
    fit<- get_fit_n(mt,3)
    #mylist  <- append(mylist, mean_print(fit[1,1], fit[1,2])) 
    fit<- get_fit_n(mt,5)
    #mylist  <- append(mylist, mean_print(fit[1,1], fit[1,2])) 
    
    #E3
    fit<- get_fit_n(mt,7)
    #mylist  <- append(mylist, mean_print(fit[1,1], fit[1,2])) 
    fit<- get_fit_n(mt,8)
    #mylist  <- append(mylist, mean_print(fit[1,1], fit[1,2])) 
    
    #a_BH
    fit<- get_fit_n(mt,13)
    mylist  <- append(mylist, mean_print(fit[1,1], fit[1,2])) 
    #a_lusher, E2,deltaE2   
    fit<- get_fit_n(mt,20)
    mylist  <- append(mylist, mean_print(fit[2,1], fit[2,2]) )
    mylist  <- append(mylist, mean_print(fit[1,1], fit[1,2])) 
    mylist  <- append(mylist, mean_print(fit[2,3], fit[2,4]))
  
    mylist  <-append(mylist, list( l0,l1,mu,g,rep ))

    df_tot_compact[count,] <-mylist
    count<- count+1
    
                    }
                
}}}}}}}}}}
renderDataTable( df_tot_compact )
```

```{r echo=FALSE, warning=FALSE}
#rows<-which(df_tot_compact["msq0"]==-4.925 & df_tot_compact["msq1"]==-4.85 )
#xx <- c(10,20,40)
#yy<-c(0.054,0.0014, 0.002)
#dy<-c(0.022, 0.0036, 0.019)
#wnlmod <- nls(yy ~ A * exp(B * xx), start = list(A = 1, B = -1), weights = dy^-2)
```

# Full Table

```{r echo=FALSE, warning=FALSE}

df_tot<- data.frame(  "L"=c(0),"T"=c(0),
                  "meff0"=c(0), "Emeff0"=c(0), "meff1"=c(0) , "Emeff1"=c(0) ,
                  "msq0"=c(0), "msq1"=c(0),
                  "lambda0"=c(0) , "lambda1"=c(0),
                  "mu"=c(0), "g"=c(0), "rep"=c(0),
                  "E2_0"=c(0),"E2_0err"=c(0),
                  "E2_1"=c(0),"E2_1err"=c(0),
                  "E2"=c(0),"E2err"=c(0),
                  "E3_0"=c(0),"E3_0err"=c(0),
                  "E3_1"=c(0),"E3_1err"=c(0),
                  "E3"=c(0),"E3err"=c(0),
                  "a_0"=c(0),"a_0err"=c(0),
                  "a_1"=c(0),"a_1err"=c(0),
                  "a_01"=c(0),"a_01err"=c(0))
count<-1
for (dir in c( "/home/marco/analysis/phi4/tuning_masses/out" )){
#for (dir in c( "Data" )){  
  for (msq1 in c(-4.9,-4.89,-4.85)){
    for (msq0 in c(-4.9,-4.95,-4.925,-4.98,-4.99,-5.0)){
      for (l0 in c(2.5)){  
        for (l1 in c(2.5)){    
          for (mu in c(5.0)){    
            for (g in c(0)){
              for (L in c(10,20,40)){
                for (T in c(24,48,128)){
                  for (rep in c(0,1,2)){
                    file1=sprintf("%s/G2t_T%d_L%d_msq0%.6f_msq1%.6f_l0%.6f_l1%.6f_mu%.6f_g%.6f_rep%d_output",
                                 dir,T,L,msq0,msq1,l0,l1,mu,g,rep)
                    if (file.exists(file1)){
                      
   
    
    columns_file<-c(1:20)  
    mylist<- list(  L,T)
    block <- read.table(file1,header=FALSE,fill = TRUE , blank.lines.skip=TRUE,skip=1,
                      col.names =columns_file)
    fit <- block[(2*(T/2)),]
    fit1<- block[(3*(T/2)),]
    mylist  <- append(mylist, list(fit[1,1], fit[1,2],fit1[1,1], fit1[1,2]) )
    mylist  <-append(mylist, list(msq0, msq1, l0,l1,mu,g,rep ))
    fit <- block[(5*(T/2)),]
    fit1<- block[(6*(T/2)),]
    mylist  <- append(mylist, list(fit[1,1], fit[1,2],fit1[1,1], fit1[1,2]) )
    fit <- block[(6*(T/2)),]
    fit1<- block[(7*(T/2)),]
    mylist  <- append(mylist, list(fit[1,1], fit[1,2],fit1[1,1], fit1[1,2]) )
    fit <- block[(8*(T/2)),]
    fit1<- block[(9*(T/2)),]
    mylist  <- append(mylist, list(fit[1,1], fit[1,2],fit1[1,1], fit1[1,2]) )
    fit <- block[(10*(T/2)),]
    fit1<- block[(11*(T/2)),]
    mylist  <- append(mylist, list(fit[1,1], fit[1,2],fit1[1,1], fit1[1,2]) )
     fit <- block[(12*(T/2)),]
    fit1<- block[(13*(T/2)),]
    mylist  <- append(mylist, list(fit[1,1], fit[1,2],fit1[1,1], fit1[1,2]) )
    df_tot[count,] <-mylist
    count<- count+1
    
                    }
                
                  }}}}}}}}}}
renderDataTable( df_tot )

```
